/* Aguará Paintball — calendario estable para reservas. No modifica script.js. */
(() => {
  "use strict";
  const state={reservations:[],byDate:new Map(),month:new Date(),selectedDate:""};
  const pad=n=>String(n).padStart(2,"0");
  const dateKey=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
  const parseDate=k=>{const [y,m,d]=k.split("-").map(Number);return new Date(y,m-1,d)};
  const time5=v=>String(v||"").slice(0,5);
  const currentTime=()=>{const d=new Date();return `${pad(d.getHours())}:${pad(d.getMinutes())}`};
  const isPast=(date,time)=>date===dateKey(new Date())&&time<=currentTime();
  const smoothBehavior=()=>window.matchMedia?.("(prefers-reduced-motion:reduce)").matches?"auto":"smooth";
  function styles(){
    if(document.getElementById("aguaraCalendarFixedStyles"))return;
    const s=document.createElement("style");s.id="aguaraCalendarFixedStyles";s.textContent=`
      .aguara-calendar-shell{grid-column:1/-1;width:100%;box-sizing:border-box;margin:0 0 18px;padding:18px;border:1px solid rgba(255,255,255,.10);border-radius:18px;background:linear-gradient(145deg,rgba(20,15,12,.97),rgba(10,10,10,.97));box-shadow:0 18px 45px rgba(0,0,0,.25)}
      .aguara-calendar-body{display:grid;grid-template-columns:minmax(0,1fr) minmax(280px,.78fr);gap:18px}.aguara-calendar-main{min-width:0}.aguara-calendar-info{display:flex;min-width:0}.aguara-calendar-info>.booking-info-editable{width:100%;height:100%;box-sizing:border-box;margin:0}
      .aguara-calendar-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px}.aguara-calendar-title{margin:0;text-transform:capitalize;font-weight:800;font-size:1.15rem}.aguara-calendar-nav{display:flex;gap:8px}.aguara-calendar-nav button{width:40px;height:40px;border:1px solid rgba(255,255,255,.14);border-radius:12px;background:#231812;color:#fff;cursor:pointer;font-size:1.15rem;font-weight:800}
      .aguara-calendar-weekdays,.aguara-calendar-grid{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:7px}.aguara-calendar-weekdays{margin-bottom:7px}.aguara-calendar-weekday{padding:6px 0;text-align:center;font-size:.72rem;color:rgba(255,255,255,.55);font-weight:800;text-transform:uppercase}
      .aguara-day{aspect-ratio:1;border:1px solid rgba(255,255,255,.10);border-radius:12px;background:#171717;color:#fff;cursor:pointer;padding:8px 6px;display:flex;align-items:center;justify-content:center;transition:transform .15s ease,border-color .15s ease,background .15s ease}.aguara-day:hover:not(:disabled){transform:translateY(-1px);border-color:rgba(255,255,255,.28)}.aguara-day:disabled{cursor:default}.aguara-day.is-outside{opacity:.28}.aguara-day.is-today{box-shadow:inset 0 0 0 1px rgba(255,255,255,.48)}.aguara-day.is-selected{border-color:#f08a35;background:#3a2418;box-shadow:0 0 0 2px rgba(240,138,53,.18)}.aguara-day.is-reserved{background:rgba(84,47,26,.72);border-color:rgba(126,67,34,.90)}.aguara-day-number{font-size:1rem;font-weight:900}
      .aguara-calendar-status{margin-top:13px;padding:11px 13px;border-radius:11px;background:rgba(0,0,0,.23);font-size:.86rem;color:rgba(255,255,255,.78)}.aguara-time-panel{margin-top:15px;padding-top:15px;border-top:1px solid rgba(255,255,255,.08)}.aguara-time-title{margin:0 0 10px;font-size:.92rem;font-weight:800}.aguara-time-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.aguara-time-card{position:relative;border:1px solid rgba(255,255,255,.12);border-radius:12px;background:#1a1a1a;color:#fff;padding:11px 12px;text-align:left;cursor:pointer;font-weight:800}.aguara-time-card small{display:block;margin-top:2px;font-size:.66rem;font-weight:700;color:rgba(255,255,255,.55)}.aguara-time-card.is-selected{border-color:#f08a35;background:#3a2418}.aguara-time-card.is-reserved{background:rgba(84,47,26,.72);border-color:#e33a3a;color:#fff;cursor:not-allowed}.aguara-time-card.is-reserved::before{content:"✕";position:absolute;top:4px;right:8px;color:#ff3131;font-size:1.05rem}.aguara-time-card.is-past{display:none}@media(max-width:900px){.aguara-calendar-body{grid-template-columns:1fr}.aguara-calendar-info{min-height:160px}}@media(max-width:640px){.aguara-calendar-shell{padding:13px}.aguara-day-number{font-size:.92rem}}
    `;document.head.appendChild(s);
  }
  async function loadReservations(){try{const r=await fetch("/api/reservations",{cache:"no-store",headers:{Accept:"application/json"}});if(!r.ok)throw new Error("No se pudieron consultar las reservas.");const p=await r.json();state.reservations=Array.isArray(p.reservas)?p.reservas:[];state.byDate=new Map();for(const row of state.reservations){const d=String(row.booking_date||row.fecha||"").slice(0,10),t=time5(row.booking_time||row.horario||"");if(d){if(!state.byDate.has(d))state.byDate.set(d,new Set());if(t)state.byDate.get(d).add(t)}}renderCalendar();renderTimes()}catch(e){console.error("CALENDARIO AGUARÁ:",e)}}
  const reserved=(d,t)=>state.byDate.get(d)?.has(t)||false;
  function moveInfo(){const b=document.getElementById("bookingInfoPublic"),slot=document.getElementById("aguaraCalendarInfoSlot");if(b&&slot&&b.parentElement!==slot)slot.appendChild(b)}
  function makeShell(){if(document.getElementById("aguaraCalendarShell")){moveInfo();return true}const input=document.getElementById("date"),grid=input?.closest(".form-grid");if(!input||!grid)return false;const shell=document.createElement("div");shell.id="aguaraCalendarShell";shell.className="aguara-calendar-shell";shell.innerHTML=`<div class="aguara-calendar-body"><div class="aguara-calendar-main"><div class="aguara-calendar-head"><h3 class="aguara-calendar-title" id="aguaraCalendarTitle"></h3><div class="aguara-calendar-nav"><button type="button" id="aguaraPrevMonth">‹</button><button type="button" id="aguaraNextMonth">›</button></div></div><div class="aguara-calendar-weekdays"><div class="aguara-calendar-weekday">Dom</div><div class="aguara-calendar-weekday">Lun</div><div class="aguara-calendar-weekday">Mar</div><div class="aguara-calendar-weekday">Mié</div><div class="aguara-calendar-weekday">Jue</div><div class="aguara-calendar-weekday">Vie</div><div class="aguara-calendar-weekday">Sáb</div></div><div class="aguara-calendar-grid" id="aguaraCalendarGrid"></div><div class="aguara-calendar-status" id="aguaraCalendarStatus">Elegí una fecha.</div><div class="aguara-time-panel" id="aguaraTimePanel"><h4 class="aguara-time-title">Horarios disponibles</h4><div class="aguara-time-grid" id="aguaraTimeGrid"></div></div></div><div class="aguara-calendar-info" id="aguaraCalendarInfoSlot"></div></div>`;grid.prepend(shell);moveInfo();document.getElementById("aguaraPrevMonth").onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()-1,1);renderCalendar()};document.getElementById("aguaraNextMonth").onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()+1,1);renderCalendar()};input.addEventListener("change",()=>{state.selectedDate=input.value;if(state.selectedDate){const d=parseDate(state.selectedDate);state.month=new Date(d.getFullYear(),d.getMonth(),1)}renderCalendar();renderTimes();loadReservations()});const time=document.getElementById("time");if(time){new MutationObserver(renderTimes).observe(time,{childList:true,subtree:true,attributes:true});time.addEventListener("change",renderTimes)}return true}
  function renderCalendar(){const grid=document.getElementById("aguaraCalendarGrid"),title=document.getElementById("aguaraCalendarTitle");if(!grid||!title)return;const y=state.month.getFullYear(),m=state.month.getMonth();title.textContent=new Date(y,m,1).toLocaleDateString("es-AR",{month:"long",year:"numeric"});grid.innerHTML="";const first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();for(let i=0;i<first;i++){const c=document.createElement("button");c.type="button";c.disabled=true;c.className="aguara-day is-outside";c.textContent=String(new Date(y,m,0).getDate()-first+i+1);grid.appendChild(c)}const today=dateKey(new Date());for(let d=1;d<=days;d++){const k=`${y}-${pad(m+1)}-${pad(d)}`,count=k>=today?(state.byDate.get(k)?.size||0):0,b=document.createElement("button");b.type="button";b.className=`aguara-day ${k===today?"is-today":""} ${k===state.selectedDate?"is-selected":""} ${count?"is-reserved":""}`;b.innerHTML=`<span class="aguara-day-number">${d}</span>`;b.addEventListener("click",()=>selectDate(k));grid.appendChild(b)}}
  function selectDate(k){const input=document.getElementById("date");if(!input)return;input.value=k;input.dispatchEvent(new Event("input",{bubbles:true}));input.dispatchEvent(new Event("change",{bubbles:true}));state.selectedDate=k;renderCalendar();renderTimes();moveInfo();requestAnimationFrame(()=>{const p=document.getElementById("aguaraTimePanel");if(p)window.scrollTo({top:Math.max(0,p.getBoundingClientRect().top+window.pageYOffset-110),behavior:smoothBehavior()})})}
  function renderTimes(){const grid=document.getElementById("aguaraTimeGrid"),select=document.getElementById("time");if(!grid||!select)return;const date=document.getElementById("date")?.value||state.selectedDate,options=Array.from(select.options).filter(o=>o.value);grid.innerHTML="";if(!date||!options.length){grid.innerHTML=`<div style="grid-column:1/-1;color:rgba(255,255,255,.52);font-size:.82rem;">Primero elegí una fecha.</div>`;return}let visible=0;for(const o of options){const t=time5(o.value);if(isPast(date,t))continue;visible++;const r=reserved(date,t),b=document.createElement("button");b.type="button";b.className=`aguara-time-card ${o.value===select.value&&!r?"is-selected":""} ${r?"is-reserved":""}`;b.disabled=r;b.innerHTML=`<span>${t}</span><small>${r?"RESERVADO":"DISPONIBLE"}</small>`;if(!r)b.onclick=()=>{select.value=o.value;select.dispatchEvent(new Event("change",{bubbles:true}));requestAnimationFrame(()=>{const n=document.getElementById("name"),target=n?.closest("label")||n;if(target)window.scrollTo({top:Math.max(0,target.getBoundingClientRect().top+window.pageYOffset-110),behavior:smoothBehavior()})})};grid.appendChild(b)}if(!visible)grid.innerHTML=`<div style="grid-column:1/-1;padding:14px;border-radius:11px;background:#25170b;border:1px solid #704318;color:#ffc98d;font-size:.84rem;">No quedan horarios disponibles para hoy. Elegí otra fecha.</div>`}
  function init(){styles();if(!makeShell())return;const input=document.getElementById("date"),today=dateKey(new Date());state.selectedDate=today;if(input){input.value=today;input.dispatchEvent(new Event("change",{bubbles:true}))}const d=parseDate(today);state.month=new Date(d.getFullYear(),d.getMonth(),1);renderCalendar();moveInfo();loadReservations()}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();