(() => {
  "use strict";
  function injectExperienceVideoStyles(){if(document.getElementById("experience-video-styles"))return;const style=document.createElement("style");style.id="experience-video-styles";style.textContent=`.experience-video{display:block;width:100%;height:330px;object-fit:cover;background:#101010;border-radius:var(--radius)}.experience-video{transform-origin:center center}@media(max-width:640px){.experience-video{height:260px}}`;document.head.appendChild(style)}
  function applyVideoPosition(video,item){if(!video)return;const x=Number(item?.position_x??50),y=Number(item?.position_y??50),zoom=Number(item?.zoom??1);video.style.objectPosition=`${x}% ${y}%`;video.style.transform=`scale(${zoom})`;video.style.transformOrigin="center center";}
  function applyMedia(media){
    const bySlot=new Map((media||[]).map(item=>[item.slot_key,item])); const hero=bySlot.get("hero_video");
    if(hero?.public_url){const video=document.querySelector(".hero-video"),source=video?.querySelector("source");if(video&&source){source.src=hero.public_url;applyVideoPosition(video,hero);video.load();video.play().catch(()=>{});}const featureImage=document.querySelector(".feature-image");if(featureImage){injectExperienceVideoStyles();const experienceVideo=document.createElement("video");experienceVideo.className="experience-video";experienceVideo.src=hero.public_url;experienceVideo.autoplay=true;experienceVideo.muted=true;experienceVideo.loop=true;experienceVideo.playsInline=true;experienceVideo.setAttribute("aria-label","Video de la experiencia Aguará");applyVideoPosition(experienceVideo,hero);featureImage.replaceWith(experienceVideo);experienceVideo.play().catch(()=>{});}}
    ["gallery_1","gallery_2","gallery_3","gallery_4","gallery_5","gallery_6"].forEach((slotKey,index)=>{const item=bySlot.get(slotKey),button=document.querySelectorAll(".gallery-item")[index],image=button?.querySelector("img");if(item?.public_url&&button&&image){button.dataset.src=item.public_url;button.dataset.title=item.title||"Aguará Paintball";image.src=item.public_url;image.alt=item.alt_text||item.title||image.alt;}});
    const firstGallery=bySlot.get("gallery_1");if(firstGallery?.public_url){const feature=document.querySelector(".feature-image");if(feature)feature.style.backgroundImage=`url('${firstGallery.public_url}')`;}
    const logo=bySlot.get("logo");if(logo?.public_url)document.querySelectorAll('img[alt="Aguará Paintball"]').forEach(image=>image.src=logo.public_url);
  }
  function initGalleryLightbox(){const lightbox=document.getElementById("lightbox"),image=document.getElementById("lightboxImg"),close=document.getElementById("closeLightbox"),prev=document.getElementById("lightboxPrev"),next=document.getElementById("lightboxNext"),counter=document.getElementById("lightboxCounter"),items=Array.from(document.querySelectorAll(".gallery-item"));if(!lightbox||!image||!items.length||lightbox.dataset.ready==="1")return;lightbox.dataset.ready="1";let current=0;const getValidItems=()=>items.filter(item=>item.dataset.src||item.querySelector("img")?.src);const show=index=>{const valid=getValidItems();if(!valid.length)return;current=(index+valid.length)%valid.length;const item=valid[current],src=item.dataset.src||item.querySelector("img")?.src;image.src=src;image.alt=item.dataset.title||item.querySelector("img")?.alt||"Aguará Paintball";if(counter)counter.textContent=`${current+1} / ${valid.length}`;lightbox.hidden=false;document.body.classList.add("lightbox-open");requestAnimationFrame(()=>lightbox.classList.add("is-open"));};const hide=()=>{lightbox.classList.remove("is-open");document.body.classList.remove("lightbox-open");setTimeout(()=>{lightbox.hidden=true;},180)};const move=direction=>show(current+direction);items.forEach((item,index)=>{item.addEventListener("click",event=>{event.preventDefault();const valid=getValidItems(),position=valid.indexOf(item);show(position>=0?position:index)});if(!item.querySelector(".gallery-hover-label")){const label=document.createElement("span");label.className="gallery-hover-label";label.textContent="VER EN GRANDE  ↗";item.appendChild(label);}});prev?.addEventListener("click",event=>{event.stopPropagation();move(-1)});next?.addEventListener("click",event=>{event.stopPropagation();move(1)});close?.addEventListener("click",hide);lightbox.addEventListener("click",event=>{if(event.target===lightbox)hide()});document.addEventListener("keydown",event=>{if(lightbox.hidden)return;if(event.key==="Escape")hide();if(event.key==="ArrowRight")move(1);if(event.key==="ArrowLeft")move(-1)});let touchStartX=0;lightbox.addEventListener("touchstart",event=>{touchStartX=event.changedTouches[0]?.clientX||0},{passive:true});lightbox.addEventListener("touchend",event=>{const endX=event.changedTouches[0]?.clientX||0,delta=endX-touchStartX;if(Math.abs(delta)>45)move(delta<0?1:-1)},{passive:true});}
  function injectCatalogStyles(){if(document.getElementById("equipment-catalog-styles"))return;const link=document.createElement("link");link.id="equipment-catalog-styles";link.rel="stylesheet";link.href="catalogo-marcadoras.css";document.head.appendChild(link)}
  function escapeHtml(value){return String(value||"").replace(/[&<>\"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[char]))}
  function ensureCatalogSection(){let section=document.getElementById("equipamiento");if(section)return section;const gallery=document.getElementById("galeria");if(!gallery)return null;section=document.createElement("section");section.id="equipamiento";section.className="section";section.innerHTML=`<div class="equipment-catalog-head"><div><p class="eyebrow" id="equipmentCatalogEyebrow">NUESTRO EQUIPAMIENTO</p><h2 id="equipmentCatalogTitle">Nuestro equipamiento.</h2></div><span class="muted" id="equipmentCatalogSubtitle">Conocé el equipamiento que proporcionamos a los jugadores durante la experiencia Aguará.</span></div><div id="equipmentCatalogGrid" class="equipment-catalog-grid"></div><div id="equipmentCatalogEmpty" class="equipment-catalog-empty" hidden>Estamos preparando nuestro equipamiento.</div>`;gallery.parentNode.insertBefore(section,gallery);injectCatalogStyles();const nav=document.querySelector("header.nav nav");if(nav&&!nav.querySelector('a[href="#equipamiento"]')){const link=document.createElement("a");link.href="#equipamiento";link.textContent="Equipamiento";nav.insertBefore(link,nav.querySelector('a[href="#galeria"]')||null)}return section}
  function applyCatalogText(){const title=localStorage.getItem("aguaraCatalogTitle"),subtitle=localStorage.getItem("aguaraCatalogSubtitle");if(title){const el=document.getElementById("equipmentCatalogTitle");if(el)el.textContent=title}if(subtitle){const el=document.getElementById("equipmentCatalogSubtitle");if(el)el.textContent=subtitle}}
  async function loadCatalog(){const section=ensureCatalogSection();if(!section)return;applyCatalogText();try{const response=await fetch("/api/public-catalog",{cache:"no-store"}),data=await response.json();if(data?.ok&&Array.isArray(data.items)){window.AguaraCatalog=data.items;const grid=document.getElementById("equipmentCatalogGrid"),empty=document.getElementById("equipmentCatalogEmpty");grid.innerHTML="";empty.hidden=data.items.length>0;data.items.forEach(item=>{const card=document.createElement("article");card.className="equipment-card";card.innerHTML=`<div class="equipment-image-wrap"><img src="${escapeHtml(item.public_url)}" alt="${escapeHtml(item.name)}" loading="lazy"></div><div class="equipment-copy"><span class="equipment-label">EQUIPAMIENTO AGUARÁ</span><h3>${escapeHtml(item.name)}</h3><p>${escapeHtml(item.description)}</p></div>`;grid.appendChild(card)})}}catch(error){console.warn("AGUARÁ EQUIPAMIENTO:",error)}}
  async function init(){initGalleryLightbox();try{const response=await fetch("/api/public-media",{cache:"no-store"}),data=await response.json();if(data?.ok)applyMedia(data.media)}catch(error){console.warn("AGUARÁ MEDIA:",error)}initGalleryLightbox();loadCatalog()}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();
