create table if not exists public.media_library (
  id bigint generated by default as identity primary key,
  slot_key text not null unique,
  media_type text not null check (media_type in ('image','video')),
  storage_path text not null,
  public_url text not null,
  title text not null default '',
  alt_text text not null default '',
  sort_order integer not null default 0,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.media_library enable row level security;

create policy if not exists "public can read enabled media"
  on public.media_library for select
  to anon, authenticated
  using (enabled = true);

insert into storage.buckets (id, name, public)
values ('site-media', 'site-media', true)
on conflict (id) do update set public = true;

insert into public.media_library (slot_key, media_type, storage_path, public_url, title, alt_text, sort_order)
values
  ('hero_video','video','hero.mp4','', 'Video principal', 'Aguará Paintball', 0),
  ('gallery_1','image','gallery-1.jpg','', 'Galería 1', 'Aguará Paintball', 1),
  ('gallery_2','image','gallery-2.jpg','', 'Galería 2', 'Partida de paintball', 2),
  ('gallery_3','image','gallery-3.jpg','', 'Galería 3', 'Jugadores de Aguará Paintball', 3),
  ('gallery_4','image','gallery-4.jpg','', 'Galería 4', 'Campo de paintball', 4),
  ('logo','image','logo.png','', 'Logo', 'Aguará Paintball', 5)
on conflict (slot_key) do nothing;
